# Default config:
#SealingDelay = "1h0m0s"
#
[API]
  ListenAddress = "/ip4/local_ip/tcp/2345/http"
  RemoteListenAddress = "local_ip:2345"
#  Timeout = "30s"
#
[Libp2p]
  ListenAddresses = ["/ip4/local_ip/tcp/23333", "/ip6/::/tcp/23333"]
  AnnounceAddresses = ["/ip4/public_ip/tcp/23333"]
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/ip4/147.75.67.199/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Dealmaking]
#  ConsiderOnlineStorageDeals = true
#  ConsiderOfflineStorageDeals = true
#  ConsiderOnlineRetrievalDeals = true
#  ConsiderOfflineRetrievalDeals = true
#  PieceCidBlocklist = []
#  ExpectedSealDuration = "12h0m0s"
  # Only accept deals from the 3 competition dealbots
  Filter = "jq -e '.Proposal.Client == \"t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i\" or .Proposal.Client == \"t1stghxhdp2w53dym2nz2jtbpk6ccd4l2lxgmezlq\" or .Proposal.Client == \"t1mcr5xkgv4jdl3rnz77outn6xbmygb55vdejgbfi\" '"

[Storage]
#  ParallelFetchLimit = 10
  AllowPreCommit1 = false
  AllowPreCommit2 = false
  AllowCommit = true
  AllowUnseal = false

[Fees]
  MaxPreCommitGasFee = "2 FIL"
  MaxCommitGasFee = "2 FIL"
  MaxWindowPoStGasFee = "50 FIL"